HTTPBodyStreamSource /  Authentication Challenge / setCredentials / setTrustAllCertificates
readdle/swift-corelibs-foundation pull request #1
Opened 2018-07-11 13:31 UTC by albertaleksieiev

URL session improvements:
- Add HTTPBodyStreamSource
- Fix curl `--anyauth` bug
-  Implement Authentication Challenge
   - credentials
   - trust certificate
- URLSession tests on real server
   - dataTaskWithHttpBody
   - dataTaskWithHttpInputStream
   - dataTaskWithBasicAuth
   - dataTaskWithDigestAuth
   - auth challenges
   - bad certificates

2018-07-11 15:19 UTC, zayass commented on Foundation/URLProtectionSpace.swift
> +        let realm = String(String(wwwAuthHeader.components(separatedBy: "realm=")[1].dropFirst()).dropLast())
`String(String(` ?

2018-07-11 15:19 UTC, zayass commented on Foundation/URLProtectionSpace.swift
> +            fatalError("Authentication failed but no Www-Authenticate header in response")
тут нельзя както помягче обработать ошибку?

2018-07-11 15:19 UTC, zayass commented on Foundation/URLSession/URLSessionTask.swift
> +            if (key as! String).lowercased().trimmingCharacters(in: .whitespacesAndNewlines) == "www-authenticate" {
зачем `as!`? оно же и так в ифе можно нормально скастить через `let key = key as? String`

2018-07-11 15:19 UTC, zayass commented on Foundation/URLSession/URLSessionTask.swift
> +                                realm = String(wwwAuthHeaderValue.dropFirst(part.lowerBound).prefix(part.length))
тут c utf8/utf16 все нормально?

2018-07-11 15:19 UTC, zayass commented on Foundation/URLSession/URLSessionTask.swift
> +    func createProtectionsSpaces(_ response: HTTPURLResponse) -> [URLProtectionSpace] {
может стоит swiftlint на этом прогнать?

2018-07-11 15:19 UTC, zayass commented on Foundation/URLSession/URLSessionTask.swift
> +                                    protocolCredentials = credential
а trust и credential одновременно не может быть?

2018-07-11 15:19 UTC, zayass commented on Foundation/URLSession/URLSessionTask.swift
> +        // TODO remove fatalError!!!!
:)

2018-07-11 15:19 UTC, zayass commented on Foundation/URLSession/URLSessionTask.swift
> +        guard let response = task.response as? HTTPURLResponse else { fatalError("No response") }
тут синхронизации не надо?

2018-07-11 15:19 UTC, zayass commented on Foundation/URLSession/URLSessionTask.swift
> +            fatalError()
там вроде внутри уже есть NSUnimplemented

2018-07-11 15:19 UTC, zayass commented on Foundation/URLSession/URLSessionTask.swift
> +    var authRequest: URLRequest? = nil
что то не вижу чтоб сюда ктото писал

2018-07-12 09:12 UTC, albertaleksieiev commented on Foundation/URLSession/URLSessionTask.swift
> +                                    protocolCredentials = credential
неа - мы делаем по аналогии как в оригинальном foundation - https://developer.apple.com/documentation/foundation/urlcredential/1413935-init

в Auth Challenge - credentials/trust 2 разных запроса

2018-07-12 09:48 UTC, albertaleksieiev commented on Foundation/URLProtectionSpace.swift
> +        let realm = String(String(wwwAuthHeader.components(separatedBy: "realm=")[1].dropFirst()).dropLast())
👍🏻

2018-07-12 09:49 UTC, albertaleksieiev commented on Foundation/URLProtectionSpace.swift
> +            fatalError("Authentication failed but no Www-Authenticate header in response")
удалил это недоразумение(метод), перенес всю логику с protectionSpace из URLSessionTask в AuthProtectionSpace

2018-07-12 09:49 UTC, albertaleksieiev commented on Foundation/URLSession/URLSessionTask.swift
> +    func createProtectionsSpaces(_ response: HTTPURLResponse) -> [URLProtectionSpace] {
👍🏻

2018-07-12 09:49 UTC, albertaleksieiev commented on Foundation/URLSession/URLSessionTask.swift
> +        // TODO remove fatalError!!!!
👀

2018-07-12 09:51 UTC, albertaleksieiev commented on Foundation/URLSession/URLSessionTask.swift
> +        guard let response = task.response as? HTTPURLResponse else { fatalError("No response") }
нет, тут все должно быть хорошо

2018-07-17 16:53 UTC, zayass requested changes

2018-07-17 16:53 UTC, zayass commented on Foundation/URLSession/http/HTTPURLProtocol.swift
> +                    // We assume that this closure not @escaping - because it can be called from curl(https://curl.haxx.se/libcurl/c/CURLOPT_SEEKFUNCTION.html)
We cannot assume this

2018-07-17 16:53 UTC, zayass commented on Foundation/URLSession/http/HTTPBodySource.swift
> +        data = data.subdata(in: 0..<Int(position))
wrong

2018-07-18 19:04 UTC, zayass approved these changes

2018-07-18 19:05 UTC, merged